/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.ControladorPrincipal;

/**
 *
 * @author Jazmin Dzib
 */
public class IngredientesRegistroP extends javax.swing.JPanel {
    private ControladorPrincipal controladorG;

    /**
     * Creates new form IngredientesRegistroP
     */
    public IngredientesRegistroP(ControladorPrincipal controladorG) {
            this.controladorG = controladorG;
            initComponents();
            controladorG.obtenerControladorMenu();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegistroPanelIngredientes = new javax.swing.JPanel();
        REGBEliminarIngrediente = new javax.swing.JButton();
        REGBEditarIngrediente = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaInventario = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        REGBAnadirIngrediente = new javax.swing.JButton();
        ANADIRINGREDIENTE = new javax.swing.JLabel();
        INVENTARIODEINGREDIENTES = new javax.swing.JLabel();
        AddIngredienteID = new javax.swing.JTextField();
        AddIngredienteCategoria = new javax.swing.JTextField();
        AddIngredienteNombre = new javax.swing.JTextField();
        AddIngredienteCantidad = new javax.swing.JTextField();

        RegistroPanelIngredientes.setBackground(new java.awt.Color(66, 96, 87));

        REGBEliminarIngrediente.setBackground(new java.awt.Color(224, 210, 159));
        REGBEliminarIngrediente.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        REGBEliminarIngrediente.setForeground(new java.awt.Color(136, 44, 17));
        REGBEliminarIngrediente.setText("Eliminar");
        REGBEliminarIngrediente.setBorderPainted(false);
        REGBEliminarIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGBEliminarIngredienteActionPerformed(evt);
            }
        });

        REGBEditarIngrediente.setBackground(new java.awt.Color(224, 210, 159));
        REGBEditarIngrediente.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        REGBEditarIngrediente.setForeground(new java.awt.Color(17, 136, 114));
        REGBEditarIngrediente.setText("Editar");
        REGBEditarIngrediente.setBorderPainted(false);
        REGBEditarIngrediente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                REGBEditarIngredienteMouseEntered(evt);
            }
        });
        REGBEditarIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGBEditarIngredienteActionPerformed(evt);
            }
        });

        TablaInventario.setAutoCreateRowSorter(true);
        TablaInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Categoría", "Nombre", "Descripción", "Cantidad", "Existencia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablaInventario.setToolTipText("");
        TablaInventario.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        TablaInventario.setColumnSelectionAllowed(true);
        TablaInventario.setShowGrid(false);
        TablaInventario.getTableHeader().setResizingAllowed(false);
        TablaInventario.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                TablaInventarioComponentAdded(evt);
            }
        });
        jScrollPane2.setViewportView(TablaInventario);

        REGBAnadirIngrediente.setBackground(new java.awt.Color(224, 210, 159));
        REGBAnadirIngrediente.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        REGBAnadirIngrediente.setText("Añadir");
        REGBAnadirIngrediente.setBorderPainted(false);
        REGBAnadirIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGBAnadirIngredienteActionPerformed(evt);
            }
        });

        ANADIRINGREDIENTE.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        ANADIRINGREDIENTE.setForeground(new java.awt.Color(215, 215, 153));
        ANADIRINGREDIENTE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ANADIRINGREDIENTE.setText("AÑADIR INGREDIENTE");
        ANADIRINGREDIENTE.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        INVENTARIODEINGREDIENTES.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        INVENTARIODEINGREDIENTES.setForeground(new java.awt.Color(215, 215, 153));
        INVENTARIODEINGREDIENTES.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        INVENTARIODEINGREDIENTES.setText("INVENTARIO DE INGREDIENTES");
        INVENTARIODEINGREDIENTES.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        AddIngredienteID.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT Condensed", 1, 18))); // NOI18N
        AddIngredienteID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddIngredienteIDActionPerformed(evt);
            }
        });

        AddIngredienteCategoria.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Categoría", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT Condensed", 1, 18))); // NOI18N
        AddIngredienteCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddIngredienteCategoriaActionPerformed(evt);
            }
        });

        AddIngredienteNombre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT Condensed", 1, 18))); // NOI18N
        AddIngredienteNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddIngredienteNombreActionPerformed(evt);
            }
        });

        AddIngredienteCantidad.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cantidad", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT Condensed", 1, 18))); // NOI18N
        AddIngredienteCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddIngredienteCantidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegistroPanelIngredientesLayout = new javax.swing.GroupLayout(RegistroPanelIngredientes);
        RegistroPanelIngredientes.setLayout(RegistroPanelIngredientesLayout);
        RegistroPanelIngredientesLayout.setHorizontalGroup(
            RegistroPanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroPanelIngredientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RegistroPanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistroPanelIngredientesLayout.createSequentialGroup()
                        .addGroup(RegistroPanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(RegistroPanelIngredientesLayout.createSequentialGroup()
                                .addComponent(AddIngredienteID, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AddIngredienteCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AddIngredienteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AddIngredienteCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(REGBAnadirIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(RegistroPanelIngredientesLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(RegistroPanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(REGBEditarIngrediente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(REGBEliminarIngrediente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(27, 27, 27))
                    .addGroup(RegistroPanelIngredientesLayout.createSequentialGroup()
                        .addGroup(RegistroPanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ANADIRINGREDIENTE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(INVENTARIODEINGREDIENTES, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        RegistroPanelIngredientesLayout.setVerticalGroup(
            RegistroPanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroPanelIngredientesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(INVENTARIODEINGREDIENTES)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegistroPanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(RegistroPanelIngredientesLayout.createSequentialGroup()
                        .addComponent(REGBEditarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(REGBEliminarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ANADIRINGREDIENTE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegistroPanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AddIngredienteID)
                    .addComponent(AddIngredienteCategoria)
                    .addComponent(AddIngredienteNombre)
                    .addComponent(AddIngredienteCantidad)
                    .addComponent(REGBAnadirIngrediente, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(RegistroPanelIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(RegistroPanelIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void REGBEliminarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGBEliminarIngredienteActionPerformed
       // eliminaringrediente();
    }//GEN-LAST:event_REGBEliminarIngredienteActionPerformed

    private void REGBEditarIngredienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_REGBEditarIngredienteMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_REGBEditarIngredienteMouseEntered

    private void REGBEditarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGBEditarIngredienteActionPerformed
       // actualizaringrediente();
    }//GEN-LAST:event_REGBEditarIngredienteActionPerformed

    private void TablaInventarioComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TablaInventarioComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaInventarioComponentAdded

    private void REGBAnadirIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGBAnadirIngredienteActionPerformed
       // agregaringrediente();
        AddIngredienteID.setText("");
        AddIngredienteCategoria.setText("");
        AddIngredienteNombre.setText("");
        AddIngredienteCantidad.setText("");
    }//GEN-LAST:event_REGBAnadirIngredienteActionPerformed

    private void AddIngredienteIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddIngredienteIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddIngredienteIDActionPerformed

    private void AddIngredienteCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddIngredienteCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddIngredienteCategoriaActionPerformed

    private void AddIngredienteNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddIngredienteNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddIngredienteNombreActionPerformed

    private void AddIngredienteCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddIngredienteCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddIngredienteCantidadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ANADIRINGREDIENTE;
    private javax.swing.JTextField AddIngredienteCantidad;
    private javax.swing.JTextField AddIngredienteCategoria;
    private javax.swing.JTextField AddIngredienteID;
    private javax.swing.JTextField AddIngredienteNombre;
    private javax.swing.JLabel INVENTARIODEINGREDIENTES;
    private javax.swing.JButton REGBAnadirIngrediente;
    private javax.swing.JButton REGBEditarIngrediente;
    private javax.swing.JButton REGBEliminarIngrediente;
    private javax.swing.JPanel RegistroPanelIngredientes;
    private javax.swing.JTable TablaInventario;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
