/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.ControladorPrincipal;
import Modelo.Buscador;
import Modelo.MenuTienda;
import Modelo.Percistencia;

import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

/**
 *
 * @author Jazmin Dzib
 */
public class MenuRegistroP extends javax.swing.JPanel implements Buscador {
    private ArrayList<MenuTienda> menuTList;
    private VistaMenu vista; //Atributo de tipo Vista.VistaMenu
    private MenuTienda menu1; //Atributo de tipo Modelo.MenuTienda
    private ControladorPrincipal controladorG;
    DefaultTableModel tablaMenu= new DefaultTableModel();

    /**
     * Creates new form Menu
     */
    public MenuRegistroP(ControladorPrincipal controladorG) {
        this.controladorG = controladorG;
        initComponents();
        controladorG.obtenerControladorMenu();
    }
    public void agregar(){

        tablaMenu.addRow(new Object[]{"", menu1.getCodigo(),menu1.getCategoria(), menu1.getProducto(), menu1.getDescripcion(), menu1.getPrecio()
        });
        Percistencia.guardarMenu(menuTList,"Menu.txt");

    }

    public int buscar(String codigo){

        return -1;
    }

    /**
     * Creates new form MenuRegistroPa
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        REGBEliminarPlatillo = new javax.swing.JButton();
        AddPlatilloDescripcion = new javax.swing.JTextField();
        REGBEditarPlatillo = new javax.swing.JButton();
        AddPlatilloCantidad = new javax.swing.JTextField();
        REGScrollInventario = new javax.swing.JScrollPane();
        TablaInventario = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        REGBAnadirPlatillo = new javax.swing.JButton();
        ANADIRPLATILLO = new javax.swing.JLabel();
        MENU = new javax.swing.JLabel();
        AddPlatilloID = new javax.swing.JTextField();
        AddPlatilloCategoria = new javax.swing.JTextField();
        AddPlatilloNombre = new javax.swing.JTextField();

        REGBEliminarPlatillo.setBackground(new java.awt.Color(224, 210, 159));
        REGBEliminarPlatillo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        REGBEliminarPlatillo.setText("Eliminar");
        REGBEliminarPlatillo.setBorderPainted(false);
        REGBEliminarPlatillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGBEliminarPlatilloActionPerformed(evt);
            }
        });

        AddPlatilloDescripcion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descripción", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT Condensed", 1, 18))); // NOI18N
        AddPlatilloDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPlatilloDescripcionActionPerformed(evt);
            }
        });

        REGBEditarPlatillo.setBackground(new java.awt.Color(224, 210, 159));
        REGBEditarPlatillo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        REGBEditarPlatillo.setText("Editar");
        REGBEditarPlatillo.setBorderPainted(false);
        REGBEditarPlatillo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                REGBEditarPlatilloMouseEntered(evt);
            }
        });
        REGBEditarPlatillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGBEditarPlatilloActionPerformed(evt);
            }
        });

        AddPlatilloCantidad.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cantidad", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT Condensed", 1, 18))); // NOI18N
        AddPlatilloCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPlatilloCantidadActionPerformed(evt);
            }
        });

        TablaInventario.setAutoCreateRowSorter(true);
        TablaInventario.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null}
                },
                new String [] {
                        "ID", "Categoría", "Nombre", "Descripción", "Cantidad", "Precio", "Existencia"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Double.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablaInventario.setToolTipText("");
        TablaInventario.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        TablaInventario.setColumnSelectionAllowed(true);
        TablaInventario.setShowHorizontalLines(true);
        TablaInventario.setShowVerticalLines(true);
        TablaInventario.getTableHeader().setResizingAllowed(false);
        TablaInventario.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                TablaInventarioComponentAdded(evt);
            }
        });
        REGScrollInventario.setViewportView(TablaInventario);

        jButton1.setBackground(new java.awt.Color(148, 172, 165));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jButton1.setText("BUSCAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        REGBAnadirPlatillo.setBackground(new java.awt.Color(224, 210, 159));
        REGBAnadirPlatillo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        REGBAnadirPlatillo.setText("Añadir");
        REGBAnadirPlatillo.setBorderPainted(false);
        REGBAnadirPlatillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGBAnadirPlatilloActionPerformed(evt);
            }
        });

        ANADIRPLATILLO.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        ANADIRPLATILLO.setForeground(new java.awt.Color(215, 215, 153));
        ANADIRPLATILLO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ANADIRPLATILLO.setText("AÑADIR PLATILLO");
        ANADIRPLATILLO.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        ANADIRPLATILLO.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        MENU.setBackground(new java.awt.Color(215, 215, 153));
        MENU.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        MENU.setForeground(new java.awt.Color(215, 215, 153));
        MENU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MENU.setText("M E N Ú");
        MENU.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        MENU.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        AddPlatilloID.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT Condensed", 1, 18))); // NOI18N
        AddPlatilloID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPlatilloIDActionPerformed(evt);
            }
        });

        AddPlatilloCategoria.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Categoría", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT Condensed", 1, 18))); // NOI18N
        AddPlatilloCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPlatilloCategoriaActionPerformed(evt);
            }
        });

        AddPlatilloNombre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT Condensed", 1, 18))); // NOI18N
        AddPlatilloNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPlatilloNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                .addComponent(REGScrollInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(REGBEliminarPlatillo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(REGBEditarPlatillo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                .addGap(72, 72, 72))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                .addComponent(MENU, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(22, 22, 22))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                .addComponent(REGBAnadirPlatillo, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(261, 261, 261))))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(ANADIRPLATILLO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(AddPlatilloID, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(AddPlatilloCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(AddPlatilloNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(AddPlatilloDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(AddPlatilloCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)))
                                                .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(MENU, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton1)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(REGBEditarPlatillo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(17, 17, 17)
                                                .addComponent(REGBEliminarPlatillo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(REGScrollInventario, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ANADIRPLATILLO, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(AddPlatilloCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(AddPlatilloNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(AddPlatilloDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(AddPlatilloCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(AddPlatilloID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(REGBAnadirPlatillo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 818, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 355, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 6, Short.MAX_VALUE)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 6, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void REGBEliminarPlatilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGBEliminarPlatilloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_REGBEliminarPlatilloActionPerformed

    private void AddPlatilloDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPlatilloDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddPlatilloDescripcionActionPerformed

    private void REGBEditarPlatilloMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_REGBEditarPlatilloMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_REGBEditarPlatilloMouseEntered

    private void REGBEditarPlatilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGBEditarPlatilloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_REGBEditarPlatilloActionPerformed

    private void AddPlatilloCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPlatilloCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddPlatilloCantidadActionPerformed

    private void TablaInventarioComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TablaInventarioComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaInventarioComponentAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

       /* TablaInventario Tablainventario=new TablaInventario();
        for (int i = 0; i < Tablainventario.selectRow(); i++) {
            String newcodigo = Tablainventario.get(i).getRow();

            if (equals(Tablainventario.get(i).getRow())) {
                System.out.println(i);
                return i;
            }//*/

}//GEN-LAST:event_jButton1ActionPerformed

    private void REGBAnadirPlatilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGBAnadirPlatilloActionPerformed
        agregar();// TODO add your handling code here:
    }//GEN-LAST:event_REGBAnadirPlatilloActionPerformed

    private void AddPlatilloIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPlatilloIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddPlatilloIDActionPerformed

    private void AddPlatilloCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPlatilloCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddPlatilloCategoriaActionPerformed

    private void AddPlatilloNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPlatilloNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddPlatilloNombreActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ANADIRPLATILLO;
    private javax.swing.JTextField AddPlatilloCantidad;
    private javax.swing.JTextField AddPlatilloCategoria;
    private javax.swing.JTextField AddPlatilloDescripcion;
    private javax.swing.JTextField AddPlatilloID;
    private javax.swing.JTextField AddPlatilloNombre;
    private javax.swing.JLabel MENU;
    private javax.swing.JButton REGBAnadirPlatillo;
    private javax.swing.JButton REGBEditarPlatillo;
    private javax.swing.JButton REGBEliminarPlatillo;
    private javax.swing.JScrollPane REGScrollInventario;
    private javax.swing.JTable TablaInventario;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}


