/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.ControladorPrincipal;
import Modelo.MenuTienda;
import Modelo.Percistencia;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jazmin Dzib
 */
public class MenuRegistro extends javax.swing.JPanel {
// End of variables declaration
    private ArrayList<MenuTienda> menuTList;
    private ControladorPrincipal controladorG;
    DefaultTableModel tablaMenu= new DefaultTableModel();

    /**
     * Creates new form MRbueno
     */
    public MenuRegistro(ControladorPrincipal controladorG) {
      this.controladorG = controladorG;
        initComponents();
        controladorG.obtenerControladorMenu();
        String ids[] = {"ID", "Categoría", "Nombre", "Precio", "Descripción" };
        tablaMenu.setColumnIdentifiers(ids);
        TablaInventario1.setModel(tablaMenu);

        this.menuTList = Percistencia.cargarMenu("Menu.txt");
        controladorG.obtenerControladorMenu().actualizarTablaPlatillos(TablaInventario1,menuTList);
    }

    void actualizarMenu(){
        int i;
        for(i=1;i<5;i++){
            int row = TablaInventario1.getSelectedRow();
            String infoingrediente = TablaInventario1.getModel().getValueAt(row, i).toString();
            switch (i) { 
                case 1 -> AddPlatilloID1.setText(infoingrediente);
                case 2 -> AddPlatilloCategoria1.setText(infoingrediente);
                case 3 -> AddPlatilloNombre1.setText(infoingrediente);
                case 4 -> AddPlatilloPrecio1.setText(infoingrediente);
                case 5 -> AddPlatilloDescripcion1.setText(infoingrediente);
            }
       }

        int fila=TablaInventario1.getSelectedRow();
        tablaMenu.setValueAt(AddPlatilloID1.getText(), fila, 0);
        tablaMenu.setValueAt(AddPlatilloCategoria1.getText(), fila, 1);
       tablaMenu.setValueAt(AddPlatilloNombre1.getText(), fila, 2);
        tablaMenu.setValueAt(AddPlatilloPrecio1.getText(), fila, 3);
        tablaMenu.setValueAt(AddPlatilloDescripcion1.getText(), fila, 4);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        REGBEliminarPlatillo1 = new javax.swing.JButton();
        AddPlatilloDescripcion1 = new javax.swing.JTextField();
        REGBEditarPlatillo1 = new javax.swing.JButton();
        AddPlatilloPrecio1 = new javax.swing.JTextField();
        REGScrollInventario1 = new javax.swing.JScrollPane();
        TablaInventario1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        BotonAñadir = new javax.swing.JButton();
        ANADIRPLATILLO1 = new javax.swing.JLabel();
        MENU1 = new javax.swing.JLabel();
        AddPlatilloID1 = new javax.swing.JTextField();
        AddPlatilloCategoria1 = new javax.swing.JTextField();
        AddPlatilloNombre1 = new javax.swing.JTextField();

        REGBEliminarPlatillo1.setBackground(new java.awt.Color(224, 210, 159));
        REGBEliminarPlatillo1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        REGBEliminarPlatillo1.setText("Eliminar");
        REGBEliminarPlatillo1.setBorderPainted(false);
        REGBEliminarPlatillo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGBEliminarPlatillo1ActionPerformed(evt);
            }
        });

        AddPlatilloDescripcion1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descripción", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT Condensed", 1, 18))); // NOI18N
        AddPlatilloDescripcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPlatilloDescripcion1ActionPerformed(evt);
            }
        });

        REGBEditarPlatillo1.setBackground(new java.awt.Color(224, 210, 159));
        REGBEditarPlatillo1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        REGBEditarPlatillo1.setText("Editar");
        REGBEditarPlatillo1.setBorderPainted(false);
        REGBEditarPlatillo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                REGBEditarPlatillo1MouseEntered(evt);
            }
        });
        REGBEditarPlatillo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGBEditarPlatillo1ActionPerformed(evt);
            }
        });

        AddPlatilloPrecio1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cantidad", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT Condensed", 1, 18))); // NOI18N
        AddPlatilloPrecio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPlatilloPrecio1ActionPerformed(evt);
            }
        });

        TablaInventario1.setAutoCreateRowSorter(true);
        TablaInventario1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Categoría", "Nombre", "Precio", "Descripción"
            }
        ));
        TablaInventario1.setToolTipText("");
        TablaInventario1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        TablaInventario1.setShowHorizontalLines(true);
        TablaInventario1.setShowVerticalLines(true);
        TablaInventario1.getTableHeader().setResizingAllowed(false);
        TablaInventario1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                TablaInventario1ComponentAdded(evt);
            }
        });
        REGScrollInventario1.setViewportView(TablaInventario1);
        TablaInventario1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jButton2.setBackground(new java.awt.Color(148, 172, 165));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jButton2.setText("BUSCAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        BotonAñadir.setBackground(new java.awt.Color(224, 210, 159));
        BotonAñadir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotonAñadir.setText("Añadir");
        BotonAñadir.setBorderPainted(false);
        BotonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAñadirActionPerformed(evt);
            }
        });

        ANADIRPLATILLO1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        ANADIRPLATILLO1.setForeground(new java.awt.Color(215, 215, 153));
        ANADIRPLATILLO1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ANADIRPLATILLO1.setText("AÑADIR PLATILLO");
        ANADIRPLATILLO1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        ANADIRPLATILLO1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        MENU1.setBackground(new java.awt.Color(215, 215, 153));
        MENU1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        MENU1.setForeground(new java.awt.Color(215, 215, 153));
        MENU1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MENU1.setText("M E N Ú");
        MENU1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        MENU1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        AddPlatilloID1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT Condensed", 1, 18))); // NOI18N
        AddPlatilloID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPlatilloID1ActionPerformed(evt);
            }
        });

        AddPlatilloCategoria1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Categoría", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT Condensed", 1, 18))); // NOI18N
        AddPlatilloCategoria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPlatilloCategoria1ActionPerformed(evt);
            }
        });

        AddPlatilloNombre1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT Condensed", 1, 18))); // NOI18N
        AddPlatilloNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPlatilloNombre1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ANADIRPLATILLO1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(AddPlatilloID1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AddPlatilloCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddPlatilloNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AddPlatilloPrecio1)
                        .addGap(18, 18, 18)
                        .addComponent(AddPlatilloDescripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addComponent(jSeparator4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 54, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(MENU1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(REGScrollInventario1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(REGBEliminarPlatillo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(REGBEditarPlatillo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(66, 66, 66))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(274, Short.MAX_VALUE)
                .addComponent(BotonAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(252, 252, 252))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MENU1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(REGBEditarPlatillo1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(REGBEliminarPlatillo1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(REGScrollInventario1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ANADIRPLATILLO1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddPlatilloCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddPlatilloNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddPlatilloID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddPlatilloPrecio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddPlatilloDescripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BotonAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 819, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 349, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 819, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 349, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void REGBEliminarPlatillo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGBEliminarPlatillo1ActionPerformed
 DefaultTableModel tblModel = (DefaultTableModel)TablaInventario1.getModel();
        
        if(TablaInventario1.getSelectedRowCount() == 1){
             String menuplato = tablaMenu.getValueAt(TablaInventario1.getSelectedRow(), 0).toString();
            tblModel.removeRow(TablaInventario1.getSelectedRow());
            controladorG.obtenerControladorMenu().eliminarPlato(menuTList, menuplato);
            
            
            Percistencia.guardarMenu(menuTList, "Menu.txt");
            
            
            
        }else{
            if(TablaInventario1.getRowCount()==0){
                JOptionPane.showMessageDialog(this, "Table is Empty.");
            }else{
                JOptionPane.showMessageDialog(this, "PLEASE SELESCT sINGLE rOW FOR DELETE.");
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_REGBEliminarPlatillo1ActionPerformed

    private void AddPlatilloDescripcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPlatilloDescripcion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddPlatilloDescripcion1ActionPerformed

    private void REGBEditarPlatillo1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_REGBEditarPlatillo1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_REGBEditarPlatillo1MouseEntered

    private void REGBEditarPlatillo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGBEditarPlatillo1ActionPerformed
    controladorG.obtenerControladorMenu().editarMenu((DefaultTableModel)TablaInventario1.getModel(), TablaInventario1, menuTList);
        ///TODO add your handling code here:
    }//GEN-LAST:event_REGBEditarPlatillo1ActionPerformed

    private void AddPlatilloPrecio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPlatilloPrecio1ActionPerformed
    
    }//GEN-LAST:event_AddPlatilloPrecio1ActionPerformed

    private void TablaInventario1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TablaInventario1ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaInventario1ComponentAdded

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        
/*TablaInventario1 Tablainventario=new TablaInventario1();
        for (int i = 0; i < Tablainventario.selectRow(); i++) {
            String newcodigo = Tablainventario.get(i).getRow();

            if (equals(Tablainventario.get(i).getRow())) {
                TablaInventario1.setRowSelectionInterval(0,1);
                return i;
            }//
        }
        /* TablaInventario Tablainventario=new TablaInventario();
        for (int i = 0; i < Tablainventario.selectRow(); i++) {
            String newcodigo = Tablainventario.get(i).getRow();

            if (equals(Tablainventario.get(i).getRow())) {
                System.out.println(i);
                return i;
            }//*/
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BotonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAñadirActionPerformed
     menuTList =new ArrayList<>();
    MenuTienda prodmenu = new MenuTienda(AddPlatilloID1.getText(),AddPlatilloCategoria1.getText(),AddPlatilloNombre1.getText(),AddPlatilloPrecio1.getText(),AddPlatilloDescripcion1.getText());
       
    AddPlatilloID1.setText("");
    AddPlatilloCategoria1.setText("");
    AddPlatilloNombre1.setText("");
    AddPlatilloPrecio1.setText("");
    AddPlatilloDescripcion1.setText("");
    menuTList.add(prodmenu);
    Percistencia.guardarMenu(menuTList,"Menu.txt");
    tablaMenu.addRow(new Object[]{prodmenu.getCodigo(),prodmenu.getCategoria(),prodmenu.getProducto(),prodmenu.getPrecio(),prodmenu.getDescripcion()
        }); // TODO add your handling code here:
    }//GEN-LAST:event_BotonAñadirActionPerformed

    private void AddPlatilloID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPlatilloID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddPlatilloID1ActionPerformed

    private void AddPlatilloCategoria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPlatilloCategoria1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddPlatilloCategoria1ActionPerformed

    private void AddPlatilloNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPlatilloNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddPlatilloNombre1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ANADIRPLATILLO1;
    private javax.swing.JTextField AddPlatilloCategoria1;
    private javax.swing.JTextField AddPlatilloDescripcion1;
    private javax.swing.JTextField AddPlatilloID1;
    private javax.swing.JTextField AddPlatilloNombre1;
    private javax.swing.JTextField AddPlatilloPrecio1;
    private javax.swing.JButton BotonAñadir;
    private javax.swing.JLabel MENU1;
    private javax.swing.JButton REGBEditarPlatillo1;
    private javax.swing.JButton REGBEliminarPlatillo1;
    private javax.swing.JScrollPane REGScrollInventario1;
    private javax.swing.JTable TablaInventario1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
