/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author Jazmin Dzib
 */
public class PerfilesRegistroP extends javax.swing.JPanel {

    /**
     * Creates new form PerfilesRegistroP
     */
    public PerfilesRegistroP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegistroPanelClientesTabla = new javax.swing.JPanel();
        CLIENTESFRECUENTES = new javax.swing.JLabel();
        REGScrollClientes = new javax.swing.JScrollPane();
        TablaClienteFrecuente = new javax.swing.JTable();
        REGBCFEditarCliente = new javax.swing.JButton();
        REGBCFEliminarCliente = new javax.swing.JButton();
        REGBCFAnadirCliente = new javax.swing.JButton();

        RegistroPanelClientesTabla.setBackground(new java.awt.Color(66, 96, 87));
        RegistroPanelClientesTabla.setPreferredSize(new java.awt.Dimension(820, 355));

        CLIENTESFRECUENTES.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        CLIENTESFRECUENTES.setForeground(new java.awt.Color(215, 215, 153));
        CLIENTESFRECUENTES.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CLIENTESFRECUENTES.setText("CLIENTES FRECUENTES");

        TablaClienteFrecuente.setAutoCreateRowSorter(true);
        TablaClienteFrecuente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Num", "Nombre(s)", "Apellido(s)", "Edad", "Domicilio", "E-Mail", "Teléfono"
            }
        ));
        TablaClienteFrecuente.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        TablaClienteFrecuente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TablaClienteFrecuente.setShowHorizontalLines(true);
        TablaClienteFrecuente.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                TablaClienteFrecuenteComponentAdded(evt);
            }
        });
        REGScrollClientes.setViewportView(TablaClienteFrecuente);

        REGBCFEditarCliente.setBackground(new java.awt.Color(215, 201, 134));
        REGBCFEditarCliente.setText("EDITAR");
        REGBCFEditarCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        REGBCFEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGBCFEditarClienteActionPerformed(evt);
            }
        });

        REGBCFEliminarCliente.setBackground(new java.awt.Color(215, 139, 134));
        REGBCFEliminarCliente.setText("ELIMINAR");
        REGBCFEliminarCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        REGBCFEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGBCFEliminarClienteActionPerformed(evt);
            }
        });

        REGBCFAnadirCliente.setBackground(new java.awt.Color(176, 215, 134));
        REGBCFAnadirCliente.setText("AÑADIR");
        REGBCFAnadirCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        REGBCFAnadirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGBCFAnadirClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegistroPanelClientesTablaLayout = new javax.swing.GroupLayout(RegistroPanelClientesTabla);
        RegistroPanelClientesTabla.setLayout(RegistroPanelClientesTablaLayout);
        RegistroPanelClientesTablaLayout.setHorizontalGroup(
            RegistroPanelClientesTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroPanelClientesTablaLayout.createSequentialGroup()
                .addGroup(RegistroPanelClientesTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistroPanelClientesTablaLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(REGScrollClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RegistroPanelClientesTablaLayout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addGroup(RegistroPanelClientesTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(REGBCFEditarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(REGBCFEliminarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                            .addComponent(REGBCFAnadirCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(120, 127, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistroPanelClientesTablaLayout.createSequentialGroup()
                .addComponent(CLIENTESFRECUENTES, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        RegistroPanelClientesTablaLayout.setVerticalGroup(
            RegistroPanelClientesTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroPanelClientesTablaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(CLIENTESFRECUENTES)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(REGScrollClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(REGBCFEditarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(REGBCFEliminarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(REGBCFAnadirCliente)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(RegistroPanelClientesTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(RegistroPanelClientesTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TablaClienteFrecuenteComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TablaClienteFrecuenteComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaClienteFrecuenteComponentAdded

    private void REGBCFEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGBCFEditarClienteActionPerformed
      /*  NuevosPerfilesRegistro NuevosPerfilesRegistro = new NuevosPerfilesRegistro();
        NuevosPerfilesRegistro.show();
        new ARegistro();
        editarcliente();
        dispose();*/

    }//GEN-LAST:event_REGBCFEditarClienteActionPerformed

    private void REGBCFEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGBCFEliminarClienteActionPerformed
        //eliminarcliente();
    }//GEN-LAST:event_REGBCFEliminarClienteActionPerformed

    private void REGBCFAnadirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGBCFAnadirClienteActionPerformed
       /* NuevosPerfilesRegistro NuevosPerfilesRegistro = new NuevosPerfilesRegistro();
        NuevosPerfilesRegistro.show();
        new ARegistro();*/
    }//GEN-LAST:event_REGBCFAnadirClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CLIENTESFRECUENTES;
    private javax.swing.JButton REGBCFAnadirCliente;
    private javax.swing.JButton REGBCFEditarCliente;
    private javax.swing.JButton REGBCFEliminarCliente;
    private javax.swing.JScrollPane REGScrollClientes;
    private javax.swing.JPanel RegistroPanelClientesTabla;
    private javax.swing.JTable TablaClienteFrecuente;
    // End of variables declaration//GEN-END:variables
}
